-- Migration script to fix NULL flags in wc_matches table
-- Run this in your Neon console to backfill any matches with NULL flags

-- Update South Korea with Czech Republic
UPDATE wc_matches
SET home_flag = 'https://flagcdn.com/w80/kr.png',
    away_flag = 'https://flagcdn.com/w80/cz.png'
WHERE fixture_id = 537328
  AND home_team = 'South Korea'
  AND away_team = 'Czechia';

-- Update Mexico with South Africa
UPDATE wc_matches
SET home_flag = 'https://flagcdn.com/w80/mx.png',
    away_flag = 'https://flagcdn.com/w80/za.png'
WHERE fixture_id = 537327
  AND home_team = 'Mexico'
  AND away_team = 'South Africa';

-- Generic fix for any remaining NULL flags
-- This creates the flags based on country names
UPDATE wc_matches
SET home_flag = CASE
  WHEN home_team = 'Argentina' THEN 'https://flagcdn.com/w80/ar.png'
  WHEN home_team = 'Australia' THEN 'https://flagcdn.com/w80/au.png'
  WHEN home_team = 'Belgium' THEN 'https://flagcdn.com/w80/be.png'
  WHEN home_team = 'Brazil' THEN 'https://flagcdn.com/w80/br.png'
  WHEN home_team = 'Cameroon' THEN 'https://flagcdn.com/w80/cm.png'
  WHEN home_team = 'Canada' THEN 'https://flagcdn.com/w80/ca.png'
  WHEN home_team = 'Chile' THEN 'https://flagcdn.com/w80/cl.png'
  WHEN home_team = 'China' THEN 'https://flagcdn.com/w80/cn.png'
  WHEN home_team = 'Colombia' THEN 'https://flagcdn.com/w80/co.png'
  WHEN home_team = 'Costa Rica' THEN 'https://flagcdn.com/w80/cr.png'
  WHEN home_team = 'Côte d''Ivoire' THEN 'https://flagcdn.com/w80/ci.png'
  WHEN home_team = 'Croatia' THEN 'https://flagcdn.com/w80/hr.png'
  WHEN home_team = 'Czech Republic' THEN 'https://flagcdn.com/w80/cz.png'
  WHEN home_team = 'Czechia' THEN 'https://flagcdn.com/w80/cz.png'
  WHEN home_team = 'Denmark' THEN 'https://flagcdn.com/w80/dk.png'
  WHEN home_team = 'Ecuador' THEN 'https://flagcdn.com/w80/ec.png'
  WHEN home_team = 'Egypt' THEN 'https://flagcdn.com/w80/eg.png'
  WHEN home_team = 'England' THEN 'https://flagcdn.com/w80/gb-eng.png'
  WHEN home_team = 'France' THEN 'https://flagcdn.com/w80/fr.png'
  WHEN home_team = 'Germany' THEN 'https://flagcdn.com/w80/de.png'
  WHEN home_team = 'Ghana' THEN 'https://flagcdn.com/w80/gh.png'
  WHEN home_team = 'Greece' THEN 'https://flagcdn.com/w80/gr.png'
  WHEN home_team = 'Guatemala' THEN 'https://flagcdn.com/w80/gt.png'
  WHEN home_team = 'Honduras' THEN 'https://flagcdn.com/w80/hn.png'
  WHEN home_team = 'Iran' THEN 'https://flagcdn.com/w80/ir.png'
  WHEN home_team = 'Japan' THEN 'https://flagcdn.com/w80/jp.png'
  WHEN home_team = 'Saudi Arabia' THEN 'https://flagcdn.com/w80/sa.png'
  WHEN home_team = 'Korea Republic' THEN 'https://flagcdn.com/w80/kr.png'
  WHEN home_team = 'South Korea' THEN 'https://flagcdn.com/w80/kr.png'
  WHEN home_team = 'Morocco' THEN 'https://flagcdn.com/w80/ma.png'
  WHEN home_team = 'Mexico' THEN 'https://flagcdn.com/w80/mx.png'
  WHEN home_team = 'Netherlands' THEN 'https://flagcdn.com/w80/nl.png'
  WHEN home_team = 'Nigeria' THEN 'https://flagcdn.com/w80/ng.png'
  WHEN home_team = 'New Zealand' THEN 'https://flagcdn.com/w80/nz.png'
  WHEN home_team = 'Norway' THEN 'https://flagcdn.com/w80/no.png'
  WHEN home_team = 'Panama' THEN 'https://flagcdn.com/w80/pa.png'
  WHEN home_team = 'Paraguay' THEN 'https://flagcdn.com/w80/py.png'
  WHEN home_team = 'Peru' THEN 'https://flagcdn.com/w80/pe.png'
  WHEN home_team = 'Poland' THEN 'https://flagcdn.com/w80/pl.png'
  WHEN home_team = 'Portugal' THEN 'https://flagcdn.com/w80/pt.png'
  WHEN home_team = 'Qatar' THEN 'https://flagcdn.com/w80/qa.png'
  WHEN home_team = 'Romania' THEN 'https://flagcdn.com/w80/ro.png'
  WHEN home_team = 'Senegal' THEN 'https://flagcdn.com/w80/sn.png'
  WHEN home_team = 'Serbia' THEN 'https://flagcdn.com/w80/rs.png'
  WHEN home_team = 'Slovakia' THEN 'https://flagcdn.com/w80/sk.png'
  WHEN home_team = 'Spain' THEN 'https://flagcdn.com/w80/es.png'
  WHEN home_team = 'Switzerland' THEN 'https://flagcdn.com/w80/ch.png'
  WHEN home_team = 'Tunisia' THEN 'https://flagcdn.com/w80/tn.png'
  WHEN home_team = 'Turkey' THEN 'https://flagcdn.com/w80/tr.png'
  WHEN home_team = 'United Arab Emirates' THEN 'https://flagcdn.com/w80/ae.png'
  WHEN home_team = 'Uruguay' THEN 'https://flagcdn.com/w80/uy.png'
  WHEN home_team = 'United States' THEN 'https://flagcdn.com/w80/us.png'
  WHEN home_team = 'USA' THEN 'https://flagcdn.com/w80/us.png'
  WHEN home_team = 'Wales' THEN 'https://flagcdn.com/w80/gb-wls.png'
  WHEN home_team = 'Scotland' THEN 'https://flagcdn.com/w80/gb-sct.png'
  WHEN home_team = 'Venezuela' THEN 'https://flagcdn.com/w80/ve.png'
  WHEN home_team = 'Bolivia' THEN 'https://flagcdn.com/w80/bo.png'
  WHEN home_team = 'South Africa' THEN 'https://flagcdn.com/w80/za.png'
  WHEN home_team = 'Albania' THEN 'https://flagcdn.com/w80/al.png'
  WHEN home_team = 'Austria' THEN 'https://flagcdn.com/w80/at.png'
  WHEN home_team = 'Azerbaijan' THEN 'https://flagcdn.com/w80/az.png'
  WHEN home_team = 'Bosnia and Herzegovina' THEN 'https://flagcdn.com/w80/ba.png'
  WHEN home_team = 'Finland' THEN 'https://flagcdn.com/w80/fi.png'
  WHEN home_team = 'Georgia' THEN 'https://flagcdn.com/w80/ge.png'
  WHEN home_team = 'Hungary' THEN 'https://flagcdn.com/w80/hu.png'
  WHEN home_team = 'Iceland' THEN 'https://flagcdn.com/w80/is.png'
  WHEN home_team = 'Ireland' THEN 'https://flagcdn.com/w80/ie.png'
  WHEN home_team = 'Israel' THEN 'https://flagcdn.com/w80/il.png'
  WHEN home_team = 'Italy' THEN 'https://flagcdn.com/w80/it.png'
  WHEN home_team = 'Kazakhstan' THEN 'https://flagcdn.com/w80/kz.png'
  WHEN home_team = 'Kosovo' THEN 'https://flagcdn.com/w80/xk.png'
  WHEN home_team = 'Luxembourg' THEN 'https://flagcdn.com/w80/lu.png'
  WHEN home_team = 'Montenegro' THEN 'https://flagcdn.com/w80/me.png'
  WHEN home_team = 'North Macedonia' THEN 'https://flagcdn.com/w80/mk.png'
  WHEN home_team = 'Malta' THEN 'https://flagcdn.com/w80/mt.png'
  WHEN home_team = 'Moldova' THEN 'https://flagcdn.com/w80/md.png'
  WHEN home_team = 'Russia' THEN 'https://flagcdn.com/w80/ru.png'
  WHEN home_team = 'San Marino' THEN 'https://flagcdn.com/w80/sm.png'
  WHEN home_team = 'Slovenia' THEN 'https://flagcdn.com/w80/si.png'
  WHEN home_team = 'Sweden' THEN 'https://flagcdn.com/w80/se.png'
  WHEN home_team = 'Ukraine' THEN 'https://flagcdn.com/w80/ua.png'
  ELSE 'https://flagcdn.com/w80/white.png'
END
WHERE home_flag IS NULL;

UPDATE wc_matches
SET away_flag = CASE
  WHEN away_team = 'Argentina' THEN 'https://flagcdn.com/w80/ar.png'
  WHEN away_team = 'Australia' THEN 'https://flagcdn.com/w80/au.png'
  WHEN away_team = 'Belgium' THEN 'https://flagcdn.com/w80/be.png'
  WHEN away_team = 'Brazil' THEN 'https://flagcdn.com/w80/br.png'
  WHEN away_team = 'Cameroon' THEN 'https://flagcdn.com/w80/cm.png'
  WHEN away_team = 'Canada' THEN 'https://flagcdn.com/w80/ca.png'
  WHEN away_team = 'Chile' THEN 'https://flagcdn.com/w80/cl.png'
  WHEN away_team = 'China' THEN 'https://flagcdn.com/w80/cn.png'
  WHEN away_team = 'Colombia' THEN 'https://flagcdn.com/w80/co.png'
  WHEN away_team = 'Costa Rica' THEN 'https://flagcdn.com/w80/cr.png'
  WHEN away_team = 'Côte d''Ivoire' THEN 'https://flagcdn.com/w80/ci.png'
  WHEN away_team = 'Croatia' THEN 'https://flagcdn.com/w80/hr.png'
  WHEN away_team = 'Czech Republic' THEN 'https://flagcdn.com/w80/cz.png'
  WHEN away_team = 'Czechia' THEN 'https://flagcdn.com/w80/cz.png'
  WHEN away_team = 'Denmark' THEN 'https://flagcdn.com/w80/dk.png'
  WHEN away_team = 'Ecuador' THEN 'https://flagcdn.com/w80/ec.png'
  WHEN away_team = 'Egypt' THEN 'https://flagcdn.com/w80/eg.png'
  WHEN away_team = 'England' THEN 'https://flagcdn.com/w80/gb-eng.png'
  WHEN away_team = 'France' THEN 'https://flagcdn.com/w80/fr.png'
  WHEN away_team = 'Germany' THEN 'https://flagcdn.com/w80/de.png'
  WHEN away_team = 'Ghana' THEN 'https://flagcdn.com/w80/gh.png'
  WHEN away_team = 'Greece' THEN 'https://flagcdn.com/w80/gr.png'
  WHEN away_team = 'Guatemala' THEN 'https://flagcdn.com/w80/gt.png'
  WHEN away_team = 'Honduras' THEN 'https://flagcdn.com/w80/hn.png'
  WHEN away_team = 'Iran' THEN 'https://flagcdn.com/w80/ir.png'
  WHEN away_team = 'Japan' THEN 'https://flagcdn.com/w80/jp.png'
  WHEN away_team = 'Saudi Arabia' THEN 'https://flagcdn.com/w80/sa.png'
  WHEN away_team = 'Korea Republic' THEN 'https://flagcdn.com/w80/kr.png'
  WHEN away_team = 'South Korea' THEN 'https://flagcdn.com/w80/kr.png'
  WHEN away_team = 'Morocco' THEN 'https://flagcdn.com/w80/ma.png'
  WHEN away_team = 'Mexico' THEN 'https://flagcdn.com/w80/mx.png'
  WHEN away_team = 'Netherlands' THEN 'https://flagcdn.com/w80/nl.png'
  WHEN away_team = 'Nigeria' THEN 'https://flagcdn.com/w80/ng.png'
  WHEN away_team = 'New Zealand' THEN 'https://flagcdn.com/w80/nz.png'
  WHEN away_team = 'Norway' THEN 'https://flagcdn.com/w80/no.png'
  WHEN away_team = 'Panama' THEN 'https://flagcdn.com/w80/pa.png'
  WHEN away_team = 'Paraguay' THEN 'https://flagcdn.com/w80/py.png'
  WHEN away_team = 'Peru' THEN 'https://flagcdn.com/w80/pe.png'
  WHEN away_team = 'Poland' THEN 'https://flagcdn.com/w80/pl.png'
  WHEN away_team = 'Portugal' THEN 'https://flagcdn.com/w80/pt.png'
  WHEN away_team = 'Qatar' THEN 'https://flagcdn.com/w80/qa.png'
  WHEN away_team = 'Romania' THEN 'https://flagcdn.com/w80/ro.png'
  WHEN away_team = 'Senegal' THEN 'https://flagcdn.com/w80/sn.png'
  WHEN away_team = 'Serbia' THEN 'https://flagcdn.com/w80/rs.png'
  WHEN away_team = 'Slovakia' THEN 'https://flagcdn.com/w80/sk.png'
  WHEN away_team = 'Spain' THEN 'https://flagcdn.com/w80/es.png'
  WHEN away_team = 'Switzerland' THEN 'https://flagcdn.com/w80/ch.png'
  WHEN away_team = 'Tunisia' THEN 'https://flagcdn.com/w80/tn.png'
  WHEN away_team = 'Turkey' THEN 'https://flagcdn.com/w80/tr.png'
  WHEN away_team = 'United Arab Emirates' THEN 'https://flagcdn.com/w80/ae.png'
  WHEN away_team = 'Uruguay' THEN 'https://flagcdn.com/w80/uy.png'
  WHEN away_team = 'United States' THEN 'https://flagcdn.com/w80/us.png'
  WHEN away_team = 'USA' THEN 'https://flagcdn.com/w80/us.png'
  WHEN away_team = 'Wales' THEN 'https://flagcdn.com/w80/gb-wls.png'
  WHEN away_team = 'Scotland' THEN 'https://flagcdn.com/w80/gb-sct.png'
  WHEN away_team = 'Venezuela' THEN 'https://flagcdn.com/w80/ve.png'
  WHEN away_team = 'Bolivia' THEN 'https://flagcdn.com/w80/bo.png'
  WHEN away_team = 'South Africa' THEN 'https://flagcdn.com/w80/za.png'
  WHEN away_team = 'Albania' THEN 'https://flagcdn.com/w80/al.png'
  WHEN away_team = 'Austria' THEN 'https://flagcdn.com/w80/at.png'
  WHEN away_team = 'Azerbaijan' THEN 'https://flagcdn.com/w80/az.png'
  WHEN away_team = 'Bosnia and Herzegovina' THEN 'https://flagcdn.com/w80/ba.png'
  WHEN away_team = 'Finland' THEN 'https://flagcdn.com/w80/fi.png'
  WHEN away_team = 'Georgia' THEN 'https://flagcdn.com/w80/ge.png'
  WHEN away_team = 'Hungary' THEN 'https://flagcdn.com/w80/hu.png'
  WHEN away_team = 'Iceland' THEN 'https://flagcdn.com/w80/is.png'
  WHEN away_team = 'Ireland' THEN 'https://flagcdn.com/w80/ie.png'
  WHEN away_team = 'Israel' THEN 'https://flagcdn.com/w80/il.png'
  WHEN away_team = 'Italy' THEN 'https://flagcdn.com/w80/it.png'
  WHEN away_team = 'Kazakhstan' THEN 'https://flagcdn.com/w80/kz.png'
  WHEN away_team = 'Kosovo' THEN 'https://flagcdn.com/w80/xk.png'
  WHEN away_team = 'Luxembourg' THEN 'https://flagcdn.com/w80/lu.png'
  WHEN away_team = 'Montenegro' THEN 'https://flagcdn.com/w80/me.png'
  WHEN away_team = 'North Macedonia' THEN 'https://flagcdn.com/w80/mk.png'
  WHEN away_team = 'Malta' THEN 'https://flagcdn.com/w80/mt.png'
  WHEN away_team = 'Moldova' THEN 'https://flagcdn.com/w80/md.png'
  WHEN away_team = 'Russia' THEN 'https://flagcdn.com/w80/ru.png'
  WHEN away_team = 'San Marino' THEN 'https://flagcdn.com/w80/sm.png'
  WHEN away_team = 'Slovenia' THEN 'https://flagcdn.com/w80/si.png'
  WHEN away_team = 'Sweden' THEN 'https://flagcdn.com/w80/se.png'
  WHEN away_team = 'Ukraine' THEN 'https://flagcdn.com/w80/ua.png'
  ELSE 'https://flagcdn.com/w80/white.png'
END
WHERE away_flag IS NULL;

-- Verify the updates
SELECT fixture_id, home_team, away_team, home_flag, away_flag FROM wc_matches WHERE fixture_id IN (537328, 537327);
